// Each title's email colours and typeface. Generated by
// scripts/build-brand-palettes.mjs from the title's own website theme.json; do
// not edit by hand. Rerun it when a title's site colours change.
export const PALETTES = {
  "smart-sme": {
    brand: "#2E3EEE",
    brandBright: "#7A86FF",
    ink: "#0A0C16",
    surface: "#F4F5FA",
    line: "#E3E5EF",
    muted: "#5A5E75",
    mutedLight: "#A9AECB",
    white: "#FFFFFF",
    font: "Space Grotesk",
    fontCss: "https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;700&display=swap",
  },
  "fleet-magazine": {
    brand: "#1D5FAA",
    brandBright: "#3A7AC6",
    ink: "#0E1726",
    surface: "#F2F5F9",
    line: "#DCE3EC",
    muted: "#5A6675",
    mutedLight: "#9AA7B6",
    white: "#FFFFFF",
    font: "Archivo",
    fontCss: "https://fonts.googleapis.com/css2?family=Archivo:wght@400;500;700&display=swap",
  },
  "golf-resort-magazine": {
    brand: "#15694A",
    brandBright: "#34A46B",
    ink: "#0E1512",
    surface: "#F2F7F2",
    line: "#E1EBE3",
    muted: "#5A6E62",
    mutedLight: "#93A99A",
    white: "#FFFFFF",
    font: "Archivo",
    fontCss: "https://fonts.googleapis.com/css2?family=Archivo:wght@400;500;700&display=swap",
  },
  "barbering-business": {
    brand: "#6E2B2B",
    brandBright: "#9A4040",
    ink: "#171310",
    surface: "#F7F4EE",
    line: "#E5DFD3",
    muted: "#6A6156",
    mutedLight: "#A99F90",
    white: "#FFFFFF",
    font: "Archivo",
    fontCss: "https://fonts.googleapis.com/css2?family=Archivo:wght@400;500;700&display=swap",
  },
  "airport-business-magazine": {
    brand: "#123B66",
    brandBright: "#5AA9F0",
    ink: "#0D1321",
    surface: "#F3F5F8",
    line: "#DCE2EA",
    muted: "#566274",
    mutedLight: "#9AA7B8",
    white: "#FFFFFF",
    font: "Archivo",
    fontCss: "https://fonts.googleapis.com/css2?family=Archivo:wght@400;500;700&display=swap",
  },
};

export function paletteFor(slug) {
  return PALETTES[slug] || null;
}
