// The monthly cost report for the director.
//
// One page about the month that has just closed, with a line on where the
// current one is heading. Everything except reads comes from fleetCosts(), so
// the PDF and the Group costs page can never disagree; reads are fetched here
// for whole calendar months because that is the period the bill covers.
import { fleetCosts } from "./fleet-costs";
import { listSites, siteCredentials } from "./site";
import { fetchPageViewsByRange } from "./analytics";

const ymd = (d) => d.toISOString().slice(0, 10);

/** Page views across every title with GA4 connected, for last month and the one before. */
async function fleetReads(now) {
  const prevStart = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() - 1, 1));
  const prevEnd = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), 0));
  const beforeStart = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() - 2, 1));
  const beforeEnd = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() - 1, 0));
  const ranges = [
    { startDate: ymd(prevStart), endDate: ymd(prevEnd), name: "prev" },
    { startDate: ymd(beforeStart), endDate: ymd(beforeEnd), name: "before" },
  ];

  const sites = await listSites();
  let prev = 0, before = 0, connected = 0;
  // Sequential on purpose: ten small requests, and the report is generated by
  // hand once a month, so politeness to the rate limiter beats speed.
  for (const site of sites) {
    try {
      const { creds } = await siteCredentials(site.id);
      const views = await fetchPageViewsByRange(creds.google_analytics, ranges);
      if (!views) continue;
      prev += views.prev;
      before += views.before;
      connected += 1;
    } catch {
      // One title's Google failing must not blank the report; the count of
      // titles included is printed beside the figure.
    }
  }
  return { prev, before, connected, of: sites.length };
}

/**
 * "Now", moved to the UK calendar month.
 *
 * The cost figures run on UTC months. Through BST the first hour of a UK month
 * is still the previous month in UTC, so a report pressed at 00:30 on 1 October
 * would have covered August. Nudging the clock to the start of the UK month
 * makes "the month before" mean what it says on a British calendar.
 */
function ukNow(now = new Date()) {
  const [y, m] = now
    .toLocaleDateString("en-CA", { timeZone: "Europe/London", year: "numeric", month: "2-digit" })
    .split("-")
    .map(Number);
  const ukMonthStart = Date.UTC(y, m - 1, 1);
  return now.getTime() < ukMonthStart ? new Date(ukMonthStart + 1000) : now;
}

/** "September 2026" — the closed month a report pressed now would cover. */
export function reportMonth(at = new Date()) {
  const now = ukNow(at);
  return new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() - 1, 1)).toLocaleString("en-GB", {
    month: "long",
    year: "numeric",
    timeZone: "UTC",
  });
}

export async function costReport({ now: at = new Date() } = {}) {
  const now = ukNow(at);
  const [costs, reads] = await Promise.all([fleetCosts({ now }), fleetReads(now)]);
  const { totals, months, month } = costs;
  const prevMonth = months.at(-2) || null;
  const beforeMonth = months.at(-3) || null;

  return {
    rate: costs.rate,
    generatedAt: now,
    month,
    lastMonth: {
      label: month.prevLabel,
      totalUsd: totals.prevUsd,
      beforeUsd: beforeMonth?.usd ?? null,
      beforeLabel: beforeMonth
        ? new Date(`${beforeMonth.key}-01T00:00:00Z`).toLocaleString("en-GB", { month: "long", timeZone: "UTC" })
        : null,
      published: totals.publishedPrev,
      produced: totals.producedPrev,
      perArticleUsd: totals.perArticlePrevUsd,
      dailyUsd: totals.prevUsd / month.prevDays,
      reads: reads.prev,
      readsBefore: reads.before,
      readsConnected: reads.connected,
      readsOf: reads.of,
      split: [
        { key: "api", label: "AI usage (Anthropic API)", usd: totals.prevUsageUsd },
        { key: "subs", label: "Software and subscriptions", usd: totals.subscriptionsUsd },
        { key: "domains", label: "Domains", usd: totals.titleFixedUsd },
      ],
    },
    thisMonth: {
      label: month.label,
      projectedUsd: totals.projectedUsd,
      soFarUsd: totals.thisUsd,
      dailyUsd: totals.dailyRateUsd,
      daysElapsed: month.daysElapsed,
      daysInMonth: month.daysInMonth,
    },
    months: months.map((m) => ({ ...m, isPrev: m === prevMonth })),
    unconfirmed: costs.unconfirmed,
  };
}
