import { PrismaClient } from "@prisma/client";
import { decryptJson } from "../lib/crypto.js";
const prisma = new PrismaClient();
const sites = await prisma.site.findMany({ select: { id: true, slug: true } });
const site = sites.find((s) => /smart/i.test(s.slug));
const rows = await prisma.siteCredential.findMany({ where: { siteId: site.id } });
const wp = Object.fromEntries(rows.map((r) => [r.kind, decryptJson(r.payloadEnc)])).wordpress;
await prisma.$disconnect();
const base = (wp.baseUrl || wp.url || "").replace(/\/$/, "");
const auth = Buffer.from(`${wp.username || wp.user}:${wp.appPassword || wp.password}`).toString("base64");
const get = (p) => fetch(`${base}/wp-json/wp/v2/${p}`, { headers: { authorization: `Basic ${auth}`, "user-agent": "CogentBot/1.0" } }).then((r) => r.json());
const uk = (d) => new Date(d + "Z").toLocaleString("en-GB", { timeZone: "Europe/London" });
const cats = Object.fromEntries((await get("categories?per_page=20&_fields=id,slug")).map((c) => [c.id, c.slug]));
const posts = await get("posts?per_page=60&status=publish&orderby=date&order=desc&_fields=id,date_gmt,title,categories,slug");
posts.forEach((p, i) => console.log(`${String(i + 1).padStart(2)}. ${uk(p.date_gmt)}  [${p.categories.map((c) => cats[c]).join(",")}]  ${p.id === 1026 ? "<<< HUGS >>> " : ""}${p.title.rendered.slice(0, 45)}`));
